version: 2.1
jobs:
  compile:
   docker:
      - image: nexgang/ubuntu:latest
   steps:
      - run:
          command: |
           git config --global user.name "Sa-Sajjad"
           git config --global user.email "sqsa93103@gmail.com"
           git config --global color.ui false
           git clone --depth=1 -b arrow-12.1 https://github.com/XenStuff/android_kernel_xiaomi_sdm660 lv && cd lv
           # /noclone3 bash build.sh --old
           /noclone3 bash <(curl -s https://raw.githubusercontent.com/XenStuff/android_kernel_xiaomi_sdm660/arrow-12.1/.circleci/build.sh)
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
      
